TodoList/TodoList/Entities/WorkTask.cs
namespace TodoList.Entities
{
    public class WorkTask
    {
        public int Id { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public DateTime ExpectedEndDate { get; set; }
        public bool IsCompleted { get; set; }
        public DateTime CreatedAt { get; set; }
    }
}

TodoList/TodoList/Entities/WorkTaskDBContext.cs
using Microsoft.EntityFrameworkCore;

namespace TodoList.Entities
{
    public class WorkTaskDBContext : DbContext
    {
        public WorkTaskDBContext(DbContextOptions<WorkTaskDBContext> options) : base(options) { }
        public DbSet<WorkTask> WorkTasks { get; set; }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {

            modelBuilder.Entity<WorkTask>()
                .HasData(new WorkTask()
                {
                    Id = 1,
                    Title = "Skosic Trawe",
                    Description = "Skosic trawe wokol domu. Wyczyscic kosiarke po wykonaniu zadania oraz odlozyc na miejsce w garazu.",
                    ExpectedEndDate = DateTime.Now.AddDays(7),
                    CreatedAt = DateTime.Now,
                    IsCompleted = false,
                },
                new WorkTask()
                {
                    Id = 2,
                    Title = "Posprzatac w domu",
                    Description = "Odkurzyc w kazdym pokoju po czym zmyc podlogi.",
                    ExpectedEndDate = DateTime.Now.AddDays(4),
                    CreatedAt = DateTime.Now.AddDays(-2),
                    IsCompleted = false,
                });
        }

    }
}

TodoList/TodoList/Models/ErrorViewModel.cs
namespace TodoList.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

TodoList/TodoList/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;
using TodoList.Models;

namespace TodoList.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }
        public IActionResult Test()
        {
            return View();
        }
        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

TodoList/TodoList/Controllers/TodoListController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using TodoList.Entities;
using TodoList.Services.Interfaces;

namespace TodoList.Controllers
{
    public class TodoListController : Controller
    {
        private readonly IWorkTaskService _workTaskService;

        public TodoListController(IWorkTaskService workTaskService)
        {
            _workTaskService = workTaskService;
        }
        public async Task<ActionResult> Index()
        {
            var workTasks = await _workTaskService.GetIncompleteTasksAsync();
            return View(workTasks);
        }
        public async Task<ActionResult> WorkTaskDetails(int id)
        {
            var workTask = await _workTaskService.GetTaskByIdAsync(id);
            return View(workTask);
        }
        [HttpGet]
        public async Task<ActionResult> FindWorkTasksByDate(DateTime date)
        {
            var workTasks = await _workTaskService.GetTasksByDateAsync(date);
            return View("Index", workTasks);
        }
        public async Task<PartialViewResult> GetNotifications()
        {
            var today = DateTime.Today;
            var tasksForToday = await _workTaskService.GetTasksByDateAsync(today);
            return PartialView("_NotificationPartial", tasksForToday);
        }
        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create(WorkTask workTask)
        {
            if (ModelState.IsValid)
            {
                workTask.CreatedAt = DateTime.Now; // Ustawienie daty utworzenia w serwisie
                await _workTaskService.CreateWorkTaskAsync(workTask);
                return RedirectToAction("Index");
            }
            return View(workTask);
        }

        public async Task<ActionResult> Edit(int id)
        {
            var workTask = await _workTaskService.GetTaskByIdAsync(id);
            return View(workTask);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit (WorkTask workTask)
        {
            if (ModelState.IsValid)
            {
                workTask.CreatedAt = DateTime.Now; // Ustawienie daty utworzenia w serwisie
                await _workTaskService.UpdateWorkTaskAsync(workTask);
                return RedirectToAction("Index");
            }
            return View(workTask);
        }

        public async Task<ActionResult> Delete(int id)
        {
            var workTask = await _workTaskService.GetTaskByIdAsync(id);
            return View(workTask);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Delete(WorkTask workTask)
        {
            await _workTaskService.DeleteWorkTaskAsync(workTask);
            return RedirectToAction("Index");
        }
    }
}

TodoList/TodoList/ViewComponents/NotificationViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System;
using System.Linq;
using System.Threading.Tasks;
using TodoList.Entities;

namespace TodoList.ViewComponents
{
    public class NotificationViewComponent : ViewComponent
    {
        private readonly WorkTaskDBContext _dbContext;

    public NotificationViewComponent(WorkTaskDBContext dbContext)
    {
        _dbContext = dbContext;
    }

    public async Task<IViewComponentResult> InvokeAsync()
    {
        var today = DateTime.Today;

        // Pobierz zadania na dzisiaj
        var tasksForToday = await _dbContext.WorkTasks
            .Where(wt => wt.ExpectedEndDate.Date == today)
            .ToListAsync();

        return View("_NotificationPartial", tasksForToday);
    }
}
}

TodoList/TodoList/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

TodoList/TodoList/Views/Home/Test.cshtml
@{
    ViewData["Title"] = "Test Page";
}

<h1>This is a test page.</h1>

TodoList/TodoList/Views/Shared/Components/Notification/_NotificationPartial.cshtml
@model IEnumerable<TodoList.Entities.WorkTask>

<div class="notification-container">
    @if (Model.Any())
    {
        <div class="notification-title"><i class="fas fa-bell"></i> Powiadomienia o zadaniach na dzisiaj:</div>
        <ul>
            @foreach (var task in Model)
            {
                <li class="notification-item">
                    <i class="fas fa-tasks"></i> @task.Title (do zrobienia do @task.ExpectedEndDate.ToShortDateString())
                </li>
            }
        </ul>
    }
    else
    {
        <p>Brak zadań do wykonania na dzisiaj.</p>
    }
</div>

TodoList/TodoList/Views/Shared/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

TodoList/TodoList/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - TodoList</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/TodoList.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="TodoList" asp-action="Index">TodoList</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="TodoList" asp-action="Index">Pokaż Wszystkie</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - TodoList - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

TodoList/TodoList/Views/TodoList/Create.cshtml
@model TodoList.Entities.WorkTask

@{
    ViewData["Title"] = "Create";
}
<div class="container">
    @await Component.InvokeAsync("Notification")
</div>
<h1>Stwórz Zadanie</h1>
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Title" class="control-label"></label>
                <input asp-for="Title" class="form-control" />
                <span asp-validation-for="Title" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <input asp-for="Description" class="form-control" />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ExpectedEndDate" class="control-label"></label>
                <input asp-for="ExpectedEndDate" class="form-control" />
                <span asp-validation-for="ExpectedEndDate" class="text-danger"></span>
            </div>
            <div class="form-group form-check">
                <label class="form-check-label">
                    <input class="form-check-input" asp-for="IsCompleted" /> @Html.DisplayNameFor(model => model.IsCompleted)
                </label>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

TodoList/TodoList/Views/TodoList/Delete.cshtml
@model TodoList.Entities.WorkTask

@{
    ViewData["Title"] = "Delete";
}

<h1>Usuń Zadanie</h1>

<h3>Jestes pewny że chcesz usunac to zadanie ? </h3>
<div class="container">
    @await Component.InvokeAsync("Notification")
</div>
<div>
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Title)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Title)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Description)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Description)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ExpectedEndDate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ExpectedEndDate)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.IsCompleted)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.IsCompleted)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.CreatedAt)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.CreatedAt)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="submit" value="Usuń" class="btn btn-danger" /> |
        <a asp-action="Index">Wróć do Strony Głownej</a>
    </form>
</div>

TodoList/TodoList/Views/TodoList/Edit.cshtml
@model TodoList.Entities.WorkTask

@{
    ViewData["Title"] = "Edit";
}
<div class="container">
    @await Component.InvokeAsync("Notification")
</div>
<h1>Edytuj Zadanie</h1>
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Title" class="control-label"></label>
                <input asp-for="Title" class="form-control" />
                <span asp-validation-for="Title" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <input asp-for="Description" class="form-control" />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ExpectedEndDate" class="control-label"></label>
                <input asp-for="ExpectedEndDate" class="form-control" />
                <span asp-validation-for="ExpectedEndDate" class="text-danger"></span>
            </div>
            <div class="form-group form-check">
                <label class="form-check-label">
                    <input class="form-check-input" asp-for="IsCompleted" /> @Html.DisplayNameFor(model => model.IsCompleted)
                </label>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Wróć do strony głownej</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

TodoList/TodoList/Views/TodoList/FindWorkTasksByDate.cshtml
@model IEnumerable<TodoList.Entities.WorkTask>

@{
    ViewData["Title"] = "FindWorkTasksByDate";
}
<p>
    <a asp-action="Create">Dodaj Zadanie</a>
</p>
<div class="container">
    @await Component.InvokeAsync("Notification")
</div>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Title)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Description)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.ExpectedEndDate)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.IsCompleted)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.CreatedAt)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Id)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Title)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Description)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ExpectedEndDate)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.IsCompleted)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.CreatedAt)
            </td>
        </tr>
}
    </tbody>
</table>

TodoList/TodoList/Views/TodoList/Index.cshtml
@model IEnumerable<TodoList.Entities.WorkTask>

@{
    ViewData["Title"] = "All Tasks";
}

<h1>Todo List</h1>

<p>
    <a asp-action="Create">Dodaj Zadanie</a>
</p>
<div class="container">
    @await Component.InvokeAsync("Notification")
</div>
<form asp-action="FindWorkTasksByDate" method="get">
    <label for="date">Wybierz datę:</label>
    <input type="date" id="date" name="date" />
    <button type="submit">Szukaj</button>
</form>

<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Title)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.ExpectedEndDate)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.IsCompleted)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.CreatedAt)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Title)
                </td>
                <td>
                    @item.ExpectedEndDate.ToShortDateString()
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.IsCompleted)
                </td>
                <td>
                    @item.CreatedAt.ToShortDateString()
                </td>
                <td>
                    @Html.ActionLink("Edytuj", "Edit", new { id = item.Id }) |
                    @Html.ActionLink("Szczegóły", "WorkTaskDetails", new { id = item.Id }) |
                    @Html.ActionLink("Usuń", "Delete", new { id = item.Id })
                </td>
            </tr>
        }
    </tbody>
</table>

TodoList/TodoList/Views/TodoList/WorkTaskDetails.cshtml
@model TodoList.Entities.WorkTask

@{
    ViewData["Title"] = "WorkTaskDetails";
}
<div class="container">
    @await Component.InvokeAsync("Notification")
</div>
<h1>Szczegóły Zadania</h1>
<div>
    <h4>WorkTask</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Title)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Title)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Description)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Description)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ExpectedEndDate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ExpectedEndDate)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.IsCompleted)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.IsCompleted)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.CreatedAt)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.CreatedAt)
        </dd>
    </dl>
</div>
<div>
    @Html.ActionLink("Edytuj", "Edit", new {  id = Model.Id  }) |
    <a asp-action="Index">Wróć Do Strony Głównej</a>
</div>